version: '3'

services:
  flask:
    build: .
    ports:
      - "8081:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000